# Generated by Django 4.0.4 on 2022-05-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('disorder_id', models.CharField(max_length=256)),
                ('expert_link', models.CharField(max_length=256)),
                ('orpha_code', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SymptomFreqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hpo_id', models.CharField(max_length=256)),
                ('disorder_id', models.CharField(max_length=256)),
                ('hpo_freq', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['hpo_freq'],
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hpo_id', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('diagnostic_criteria', models.CharField(blank=True, max_length=256, null=True)),
                ('diseases', models.ManyToManyField(blank=True, to='rare_conditions.disease')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
